### ISSUE TITLE
Задача $geoIntersects - интеграция задачи на степик

### ISSUE THREAD

**Issue by MilanaGaiduk** [moevm/mse_nosql_tasks_course#22]
Сделать работоспособный step, в котором работает задача

**Comment by MilanaGaiduk** [comment]
https://github.com/moevm/mse_nosql_tasks_course/pull/44

**Comment by zmm** [comment]
Написал комментарии в PR. 
Также обратите внимание на то, что я в stepik заменил тип бокса на mongodb - это как раз тот, в котором нам установили монго.
