### ISSUE TITLE
Простая задача на создание индекса - интеграция задачи на степик

### ISSUE THREAD

**Issue by MilanaGaiduk** [moevm/mse_nosql_tasks_course#27]
Создать работоспособный step, в котором работает задача

**Comment by zmm** [comment]
Кажется, что в вашей задаче на stepik 1) две задачи (степа) 2) указан неправильный образ (нужен dbms)

**Comment by MilanaGaiduk** [comment]
https://stepik.org/lesson/61150/step/1?unit=38268
