### ISSUE TITLE
 баг - correct_answer не удаляется

### ISSUE THREAD

**Issue by Awethon** [moevm/mse_nosql_tasks_course#46]
даже через rm -f не удаляется, что делать то... спасите помогите
(аналогичным образом файл решения успешно удаляется)

**Comment by Awethon** [comment]
fixed via sudo

**Comment by Awethon** [comment]
https://github.com/moevm/mse_nosql_tasks_course/pull/62
https://github.com/moevm/mse_nosql_tasks_course/pull/63

**Comment by zmm** [comment]
Смержил PR, добавьте пожалуйста результаты в задачу по Intersects https://stepik.org/lesson/57639/step/2?unit=35379

**Comment by zmm** [comment]
https://stepik.org/lesson/57639/step/2?unit=35379 перезалил задачу из мастера, correct_answer все равно остается.
