### ISSUE TITLE
Правки в презентации

### ISSUE THREAD

**Issue by zmm** [moevm/mse_nosql_tasks_course#50]
1. Давайте смержим презентацию в мастер (она пока в ветке geointersects) после всех исправлений
2. Титульник:
- презентация окончания этапа - презентация окончания  **второго** этапа
- ваши фамилии и инициалы,  группы
3. Результат - давайте добавим на этот слайд ссылки на наш репозиторий + на сам курс

**Comment by MilanaGaiduk** [comment]
https://github.com/moevm/mse_nosql_tasks_course/pull/51
