### ISSUE TITLE
Краткая теория - Создание индексов 

### ISSUE THREAD

**Issue by zmm** [moevm/mse_nosql_tasks_course#55]

**Comment by MilanaGaiduk** [comment]
https://github.com/moevm/mse_nosql_tasks_course/pull/68

**Comment by MilanaGaiduk** [comment]
шаг с теорией на stepik: https://stepik.org/lesson/61150/step/1?alternative=2

**Comment by zmm** [comment]
На степике все ок, в PR проблема с кодировкой.
