### ISSUE TITLE
Микрозадачи (без терминала) на geojson

### ISSUE THREAD

**Issue by zmm** [moevm/mse_nosql_tasks_course#65]
Например:
- по готовому geojson и вервису визуализации определить, что лежит в полигоне

**Comment by MilanaGaiduk** [comment]
https://github.com/moevm/mse_nosql_tasks_course/pull/75

**Comment by MilanaGaiduk** [comment]
https://stepik.org/lesson/60657/step/2?unit=37944
https://stepik.org/lesson/60657/step/3?unit=37944

**Comment by zmm** [comment]
Милана, давайте сделаем для каждого из элементов в обоих заданиях следующее значение атрибута properties :  
`"properties": {"number":"НОМЕР_ЭЛЕМЕНТА"}`

Это сильно упростит жизнь тем, кто будет делать задачки.
