### ISSUE TITLE
мелкие баги по заданию geoindex

### ISSUE THREAD

**Issue by zmm** [moevm/mse_nosql_tasks_course#70]
- кажется, что проходящий задание может скопировать пример из абзаца "Создание индекса 2dsphere"  и не сильно вдумываясь его сделать. Предлагаю пример построения 2dsphere убрать, а вместо него добавить выше пример для построения простого индекса
- необходимо уточнить сообщение об ошибке вот здесь https://github.com/moevm/mse_nosql_tasks_course/pull/67/files#diff-a2dc95e71a9c9aea6bb63b0ece94b4c6R6
- в созданной машине остается папка с содержимым репозитория, ее необходимо удалять в скриптах

**Comment by MilanaGaiduk** [comment]
Теорию на степике исправила. https://stepik.org/lesson/61150/step/1?unit=38268

https://github.com/moevm/mse_nosql_tasks_course/pull/72
